<?php if ($block->getCurrencyCount() > 1) : ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="language-<?= $block->escapeHtml($currentCurrencyCode) ?>">
                    <span class="currency-code"><?= $block->escapeHtml($currentCurrencyCode) ?></span>
                    <span class="currency-separator">-</span>
                    <?php if ($currencies[$currentCurrencyCode]) : ?>
                        <span class="currency-title">
                            <?= $block->escapeHtml($currencies[$currentCurrencyCode]) ?>
                        </span>
                    <?php endif ?>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($currencies as $_code => $_name) : ?>
                    <?php if ($_code != $currentCurrencyCode) : ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'>
                                <span class="currency-code"><?= $block->escapeHtml($_code) ?></span>
                                <span class="currency-separator">-</span>
                                <span class="currency-title"><?= $block->escapeHtml($_name) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
