<?php if (!$topLinks = $this->getLayout()->getBlock('top.links')) return; ?>
<div class="switcher customer switcher-customer" data-ui-id="customer-switcher" id="switcher-customer">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('My Account')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-customer-trigger"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <a class="link"
               href="<?= $block->escapeUrl($this->getUrl('customer/account')) ?>"
               title="<?= $block->escapeHtml(__('My Account')) ?>">
                <i class="icon"></i>
                <span class="text"><?= $block->escapeHtml(__('My Account')) ?></span>
            </a>
        </div>
        <?= $topLinks->setCssClass('dropdown switcher-dropdown')->toHtml(); ?>
    </div>
</div>
