<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Catalog\Block\Product\ListProduct $parentBlock */
$parentBlock = $this->getParentBlock();

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $parentBlock->getData('outputHelper');

/** @var \Magento\Catalog\Model\Product $_product */
$_product = $block->getProduct();
?>

<?php
    $_productNameStripped = $parentBlock->stripTags($_product->getName(), null, true);
    $_productDescription = $_product->getShortDescription();
?>

<?php if ($_productDescription) : ?>
    <div class="product description product-item-description">
        <?= /* @noEscape */ $_helper->productAttribute($_product, $_productDescription, 'short_description') ?>
        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
           title="<?= /* @noEscape */ $_productNameStripped ?>"
           class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
    </div>
<?php endif ?>
