<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Catalog\Block\Product\ListProduct $parentBlock */
$parentBlock = $this->getParentBlock();

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $parentBlock->getData('outputHelper');

/** @var \Magento\Catalog\Model\Product $_product */
$_product = $block->getProduct();

if ($parentBlock->getMode() === 'grid') {
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}
?>

<?= $parentBlock->getReviewsSummaryHtml($_product, $templateType) ?>
